### ISSUE TITLE
Missing model file

### ISSUE THREAD

**Issue by tytyui** [PhoenixOrg/PhoenixEngine#6]
There is something wrong when I run "game.exe",a model file called "Fighter-Soul.obj" in "Asset" folder is not committed.
![image](https://cloud.githubusercontent.com/assets/4616674/11317096/7f05e162-905b-11e5-8b76-3db05d5b5329.png)

**Comment by PhilipDiehl** [comment]
Unfortunately, I can't upload these models to github as they may have been previously purchased.  When the engine's a little further along, we will be uploading the assets we'll be using (assuming they're free).
