### ISSUE TITLE
Shader Error

### ISSUE THREAD

**Issue by tytyui** [PhoenixOrg/PhoenixEngine#7]
There is an error in "Model_FS.txt".
The "FSIn_Normal" is not used,this will cause an error when call "GetShaderUniformLocation()".

![image](https://cloud.githubusercontent.com/assets/4616674/11317527/83d68c3a-906c-11e5-8be4-5b11dd4eb357.png)

**Comment by PhilipDiehl** [comment]
I've disabled the use of that parameter for now, so you should no longer see this error.
